<img src="https://raw.githubusercontent.com/rbizoi/PythonFormation/main/images/e-brasil.png" width="850">

https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce

# Les imports et initialisations des variables

In [1]:
from datetime import datetime
import pandas as pd, numpy as np, os, warnings, seaborn as sns, pickle, re, unicodedata
from datetime import datetime as dt
import sqlalchemy

warnings.filterwarnings(action="ignore")

url = sqlalchemy.URL.create(
    drivername="postgresql+psycopg2",
    username="formation",
    password="formation",
    host="postgres-source",
    port=5432,
    database="ebrasil",
)

engine = sqlalchemy.create_engine( 
    url, #url = "postgresql://formation:formation@postgres-source:5432/formation"
    pool_pre_ping=True,
)

print("connecting with engine " + str(engine)) 

with engine.connect() as connection:
    print(connection.execute(sqlalchemy.text("SELECT current_database(), current_user")).fetchone())

connecting with engine Engine(postgresql+psycopg2://formation:***@postgres-source:5432/ebrasil)
('ebrasil', 'formation')

## Liste fichiers de données

In [2]:
!pwd

/opt/spark/notebooks/python

In [3]:
!ls -al /opt/spark/data/ebrasil

total 111648
drwxrwxrwx 1 root root      512 Sep 24 08:45 .
drwxrwxrwx 1 root root      512 Sep 24 15:33 ..
-rwxrwxrwx 1 root root  9033957 Oct  6  2019 olist_customers_dataset.csv
-rwxrwxrwx 1 root root 49435295 Sep 24 08:45 olist_geolocation_dataset.csv
-rwxrwxrwx 1 root root 15438671 Oct  6  2019 olist_order_items_dataset.csv
-rwxrwxrwx 1 root root  5777138 Oct  6  2019 olist_order_payments_dataset.csv
-rwxrwxrwx 1 root root 14409007 Oct  6  2019 olist_order_reviews_dataset.csv
-rwxrwxrwx 1 root root 17654914 Oct  6  2019 olist_orders_dataset.csv
-rwxrwxrwx 1 root root  2379446 Oct  6  2019 olist_products_dataset.csv
-rwxrwxrwx 1 root root   177799 Sep 28  2020 olist_sellers_dataset.csv
-rwxrwxrwx 1 root root     2613 Jan 10  2024 product_category_name_translation.csv

## Changement de répertoire

In [4]:
os.chdir("/opt/spark/data/ebrasil")

# Les fichiers de données

In [5]:
donnees = pd.read_csv('olist_orders_dataset.csv',parse_dates=True,infer_datetime_format=True)

# DataFrame $orders$ Commandes

In [6]:
donnees.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [7]:
donnees.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

## Conversions des dates

In [8]:
donnees['purchase_timestamp']= pd.to_datetime(donnees.order_purchase_timestamp, format='%Y-%m-%d %H:%M:%S',errors='ignore')
donnees['approved_at']=pd.to_datetime(donnees.order_approved_at, format='%Y-%m-%d %H:%M:%S',errors='ignore')
donnees['delivered_carrier']= pd.to_datetime(donnees.order_delivered_carrier_date, format='%Y-%m-%d %H:%M:%S',errors='ignore')
donnees['delivered_customer']= pd.to_datetime(donnees.order_delivered_customer_date, format='%Y-%m-%d %H:%M:%S',errors='ignore')
donnees['estimated_delivery']= pd.to_datetime(donnees.order_estimated_delivery_date, format='%Y-%m-%d %H:%M:%S',errors='ignore')
donnees['status']=donnees['order_status']

In [9]:
donnees.drop(columns=['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date','order_status'],inplace=True)

In [10]:
donnees.dtypes

order_id                      object
customer_id                   object
purchase_timestamp    datetime64[ns]
approved_at           datetime64[ns]
delivered_carrier     datetime64[ns]
delivered_customer    datetime64[ns]
estimated_delivery    datetime64[ns]
status                        object
dtype: object

In [11]:
donnees.isna().sum()

order_id                 0
customer_id              0
purchase_timestamp       0
approved_at            160
delivered_carrier     1783
delivered_customer    2965
estimated_delivery       0
status                   0
dtype: int64

In [12]:
donnees.shape

(99441, 8)

In [13]:
donnees.order_id.nunique(),donnees.shape

(99441, (99441, 8))

In [14]:
len(donnees.status.unique()),donnees.shape

(8, (99441, 8))

In [15]:
donnees.status.unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

## Variables suplimentaires

In [16]:
donnees['annee']           = donnees.purchase_timestamp.dt.year
donnees['mois']            = donnees.purchase_timestamp.dt.month
donnees['annee_mois']      = donnees.purchase_timestamp.dt.year*100 + donnees.purchase_timestamp.dt.month
donnees['jour']            = donnees.purchase_timestamp.dt.day
donnees['annee_jour']      = donnees.purchase_timestamp.dt.year*1000 + donnees.purchase_timestamp.dt.day
donnees['jour_semaine']    = donnees.purchase_timestamp.dt.day_of_week
donnees['trimestre']       = donnees.purchase_timestamp.dt.quarter
donnees['annee_trimestre'] = donnees.purchase_timestamp.dt.year*10 + donnees.purchase_timestamp.dt.quarter
donnees['semaine']         = donnees.purchase_timestamp.dt.isocalendar().week.astype('int32')
donnees['annee_semaine']   = (donnees.purchase_timestamp.dt.year*100 + donnees.purchase_timestamp.dt.isocalendar().week).astype('int32')
donnees['heure']           = donnees.purchase_timestamp.dt.hour

# Intervalle depuis la commande
donnees['approuvee']       = (donnees.approved_at        - donnees.purchase_timestamp).dt.seconds/60/60
donnees['envoyee'  ]       = (donnees.delivered_carrier  - donnees.purchase_timestamp).dt.seconds/60/60
donnees['livree'   ]       = (donnees.delivered_customer - donnees.purchase_timestamp).dt.seconds/60/60
donnees['estimee'  ]       = (donnees.estimated_delivery - donnees.purchase_timestamp).dt.seconds/60/60

In [17]:
donnees.columns

Index(['order_id', 'customer_id', 'purchase_timestamp', 'approved_at',
       'delivered_carrier', 'delivered_customer', 'estimated_delivery',
       'status', 'annee', 'mois', 'annee_mois', 'jour', 'annee_jour',
       'jour_semaine', 'trimestre', 'annee_trimestre', 'semaine',
       'annee_semaine', 'heure', 'approuvee', 'envoyee', 'livree', 'estimee'],
      dtype='object')

In [18]:
donnees[['purchase_timestamp', 'approved_at',
       'delivered_carrier', 'delivered_customer', 'estimated_delivery',
       'status', 'annee', 'mois', 'annee_mois', 'jour', 'annee_jour',
       'jour_semaine', 'trimestre', 'annee_trimestre', 'semaine',
       'annee_semaine', 'heure']].head()

,purchase_timestamp,approved_at,delivered_carrier,delivered_customer,estimated_delivery,status,annee,mois,annee_mois,jour,annee_jour,jour_semaine,trimestre,annee_trimestre,semaine,annee_semaine,heure
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,delivered,2017,10,201710,2,2017002,0,4,20174,40,201740,10
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,delivered,2018,7,201807,24,2018024,1,3,20183,30,201830,20
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,delivered,2018,8,201808,8,2018008,2,3,20183,32,201832,8
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,delivered,2017,11,201711,18,2017018,5,4,20174,46,201746,19
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,delivered,2018,2,201802,13,2018013,1,1,20181,7,201807,21

In [19]:
donnees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            99441 non-null  object
 1   customer_id         99441 non-null  object
 2   purchase_timestamp  99441 non-null  datetime64[ns]
 3   approved_at         99281 non-null  datetime64[ns]
 4   delivered_carrier   97658 non-null  datetime64[ns]
 5   delivered_customer  96476 non-null  datetime64[ns]
 6   estimated_delivery  99441 non-null  datetime64[ns]
 7   status              99441 non-null  object
 8   annee               99441 non-null  int32
 9   mois                99441 non-null  int32
 10  annee_mois          99441 non-null  int32
 11  jour                99441 non-null  int32
 12  annee_jour          99441 non-null  int32
 13  jour_semaine        99441 non-null  int32
 14  trimestre           99441 non-null  int32
 15  annee_trimestre     99441 non-null  int32
 16  semaine             99441 non-null  int32
 17  annee_semaine       99441 non-null  int32
 18  heure               99441 non-null  int32
 19  approuvee           99281 non-null  float64
 20  envoyee             97658 non-null  float64
 21  livree              96476 non-null  float64
 22  estimee             99441 non-null  float64
dtypes: datetime64[ns](5), float64(4), int32(11), object(3)
memory usage: 13.3+ MB

In [20]:
donnees.head()

,order_id,customer_id,purchase_timestamp,approved_at,delivered_carrier,delivered_customer,estimated_delivery,status,annee,mois,...,jour_semaine,trimestre,annee_trimestre,semaine,annee_semaine,heure,approuvee,envoyee,livree,estimee
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,delivered,2017,10,...,0,4,20174,40,201740,10,0.178333,8.974167,10.477778,13.057500
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,delivered,2018,7,...,1,3,20183,30,201830,20,6.713889,17.823056,18.768889,3.306389
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,delivered,2018,8,...,2,3,20183,32,201832,8,0.276111,5.186389,9.461111,15.353056
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,delivered,2017,11,...,5,4,20174,46,201746,19,0.298056,18.198056,5.010000,4.531667
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,delivered,2018,2,...,1,1,20181,7,201807,21,1.030556,22.465278,20.973056,2.689167

## Sauvegarde en parquet

In [21]:
os.chdir("/opt/spark/notebooks/ecommerce")

In [22]:
donnees.to_parquet('orders.parquet',compression='gzip', engine='pyarrow')

In [23]:
pd.read_parquet('orders.parquet').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            99441 non-null  object
 1   customer_id         99441 non-null  object
 2   purchase_timestamp  99441 non-null  datetime64[ns]
 3   approved_at         99281 non-null  datetime64[ns]
 4   delivered_carrier   97658 non-null  datetime64[ns]
 5   delivered_customer  96476 non-null  datetime64[ns]
 6   estimated_delivery  99441 non-null  datetime64[ns]
 7   status              99441 non-null  object
 8   annee               99441 non-null  int32
 9   mois                99441 non-null  int32
 10  annee_mois          99441 non-null  int32
 11  jour                99441 non-null  int32
 12  annee_jour          99441 non-null  int32
 13  jour_semaine        99441 non-null  int32
 14  trimestre           99441 non-null  int32
 15  annee_trimestre     99441 non-null  int32
 16  semaine             99441 non-null  int32
 17  annee_semaine       99441 non-null  int32
 18  heure               99441 non-null  int32
 19  approuvee           99281 non-null  float64
 20  envoyee             97658 non-null  float64
 21  livree              96476 non-null  float64
 22  estimee             99441 non-null  float64
dtypes: datetime64[ns](5), float64(4), int32(11), object(3)
memory usage: 13.3+ MB

In [24]:
!ls -al

total 9268
drwxr-xr-x 1 spark spark     512 Sep 24 16:33 .
drwxrwxrwx 1 root  root      512 Sep 24 15:55 ..
-rw-r--r-- 1 spark spark 9489433 Sep 24 16:33 orders.parquet

## Sauvegarde dans la base de données

In [25]:
donnees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            99441 non-null  object
 1   customer_id         99441 non-null  object
 2   purchase_timestamp  99441 non-null  datetime64[ns]
 3   approved_at         99281 non-null  datetime64[ns]
 4   delivered_carrier   97658 non-null  datetime64[ns]
 5   delivered_customer  96476 non-null  datetime64[ns]
 6   estimated_delivery  99441 non-null  datetime64[ns]
 7   status              99441 non-null  object
 8   annee               99441 non-null  int32
 9   mois                99441 non-null  int32
 10  annee_mois          99441 non-null  int32
 11  jour                99441 non-null  int32
 12  annee_jour          99441 non-null  int32
 13  jour_semaine        99441 non-null  int32
 14  trimestre           99441 non-null  int32
 15  annee_trimestre     99441 non-null  int32
 16  semaine             99441 non-null  int32
 17  annee_semaine       99441 non-null  int32
 18  heure               99441 non-null  int32
 19  approuvee           99281 non-null  float64
 20  envoyee             97658 non-null  float64
 21  livree              96476 non-null  float64
 22  estimee             99441 non-null  float64
dtypes: datetime64[ns](5), float64(4), int32(11), object(3)
memory usage: 13.3+ MB

In [26]:
with engine.connect() as connection:
    donnees.to_sql('orders',
               con=connection,
               if_exists='replace',
               index=False,
               dtype={ 
                        "order_id"           :sqlalchemy.types.String(80),
                        "customer_id"        :sqlalchemy.types.String(80),
                        "purchase_timestamp" :sqlalchemy.types.DateTime(),
                        "approved_at"        :sqlalchemy.types.DateTime(),
                        "delivered_carrier"  :sqlalchemy.types.DateTime(),
                        "delivered_customer" :sqlalchemy.types.DateTime(),
                        "estimated_delivery" :sqlalchemy.types.DateTime(),
                        "status"             :sqlalchemy.types.String(80),
                        "annee"              :sqlalchemy.types.Integer(),
                        "mois"               :sqlalchemy.types.Integer(),
                        "annee_mois"         :sqlalchemy.types.Integer(),
                        "jour"               :sqlalchemy.types.Integer(),
                        "annee_jour"         :sqlalchemy.types.Integer(),
                        "jour_semaine"       :sqlalchemy.types.Integer(),
                        "trimestre"          :sqlalchemy.types.Integer(),
                        "annee_trimestre"    :sqlalchemy.types.Integer(),
                        "semaine"            :sqlalchemy.types.Integer(),
                        "annee_semaine"      :sqlalchemy.types.Integer(),
                        "heure"              :sqlalchemy.types.Integer(),
                        "approuvee"          :sqlalchemy.types.Float(),
                        "envoyee"            :sqlalchemy.types.Float(),
                        "livree"             :sqlalchemy.types.Float(),
                        "estimee"            :sqlalchemy.types.Float()
               })

In [27]:
with engine.connect() as connection:
    requete  = "select count(*) from orders"
    print(pd.read_sql_query(requete, connection))

   count
0  99441