<img src="https://raw.githubusercontent.com/rbizoi/PythonFormation/main/images/e-brasil.png" width="850">


https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce

# Les imports et initialisations des variables

In [1]:
from datetime import datetime
import pandas as pd, numpy as np, os, warnings, seaborn as sns, pickle, re, unicodedata
from datetime import datetime as dt
import sqlalchemy

warnings.filterwarnings(action="ignore")

engine = sqlalchemy.create_engine("postgresql://formation:formation@localhost:5432/ebrasil")
connection = engine.connect()
print("connecting with engine " + str(engine))

connecting with engine Engine(postgresql://formation:***@localhost:5432/ebrasil)

## Liste fichiers de données

In [2]:
!dir ..\donnees\ebrasil

 Le volume dans le lecteur C s'appelle Windows
 Le num‚ro de s‚rie du volume est 7E56-F105

 R‚pertoire de C:\dev\PythonFormation\donnees\ebrasil

10/01/2024  11:34    <DIR>          .
04/06/2026  10:58    <DIR>          ..
06/10/2019  21:27         9ÿ033ÿ957 olist_customers_dataset.csv
06/10/2019  21:27        61ÿ273ÿ883 olist_geolocation_dataset.csv
06/10/2019  21:27        17ÿ654ÿ914 olist_orders_dataset.csv
06/10/2019  21:27        15ÿ438ÿ671 olist_order_items_dataset.csv
06/10/2019  21:27         5ÿ777ÿ138 olist_order_payments_dataset.csv
06/10/2019  21:27        14ÿ409ÿ007 olist_order_reviews_dataset.csv
06/10/2019  21:27         2ÿ379ÿ446 olist_products_dataset.csv
28/09/2020  08:52           177ÿ799 olist_sellers_dataset.csv
10/01/2024  11:19             2ÿ613 product_category_name_translation.csv
               9 fichier(s)      126ÿ147ÿ428 octets
               2 R‚p(s)  155ÿ003ÿ441ÿ152 octets libres

## Changement de répertoire

In [3]:
os.chdir(r"../donnees")

# DataFrame $reviews$

In [4]:
donnees = pd.read_csv(os.path.join('ebrasil', 'olist_order_reviews_dataset.csv'))
donnees.rename(columns={col:col.replace('review_','') for col in donnees.columns[2:]},inplace=True)
donnees.creation_date = pd.to_datetime(donnees.creation_date, format='%Y-%m-%d %H:%M:%S',errors='ignore')
donnees.answer_timestamp = pd.to_datetime(donnees.answer_timestamp, format='%Y-%m-%d %H:%M:%S',errors='ignore')
donnees = donnees.merge(pd.read_parquet('./ecommerce/orders.parquet')[['order_id', 'purchase_timestamp']],on='order_id')

In [5]:
donnees.head()

,review_id,order_id,score,comment_title,comment_message,creation_date,answer_timestamp,purchase_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18,2018-01-18 21:46:59,2018-01-11 15:30:49
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10,2018-03-11 03:05:13,2018-02-28 12:25:19
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17,2018-02-18 14:36:24,2018-02-03 09:56:22
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06,2017-04-09 17:41:13
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53,2018-02-10 10:59:03

In [6]:
donnees['creation'] = ((donnees.creation_date - donnees.purchase_timestamp).dt.days*24+(donnees.creation_date - donnees.purchase_timestamp).dt.seconds/60/60).astype('int32')
donnees['answer'] = ((donnees.answer_timestamp - donnees.creation_date).dt.days*24+(donnees.answer_timestamp - donnees.creation_date).dt.seconds/60/60).astype('int32')
donnees.score = donnees.score.astype('int16')
donnees['comment'] = donnees.comment_message.apply(lambda x : len(str(x))).astype('int16')
donnees.head()

,review_id,order_id,score,comment_title,comment_message,creation_date,answer_timestamp,purchase_timestamp,creation,answer,comment
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18,2018-01-18 21:46:59,2018-01-11 15:30:49,152,21,3
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10,2018-03-11 03:05:13,2018-02-28 12:25:19,227,27,3
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17,2018-02-18 14:36:24,2018-02-03 09:56:22,326,38,3
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06,2017-04-09 17:41:13,270,22,37
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53,2018-02-10 10:59:03,445,34,100

In [7]:
donnees.order_id.nunique(),donnees.shape[0]

(99441, 100000)

In [8]:
donnees.dtypes

review_id                     object
order_id                      object
score                          int16
comment_title                 object
comment_message               object
creation_date         datetime64[ns]
answer_timestamp      datetime64[ns]
purchase_timestamp    datetime64[ns]
creation                       int32
answer                         int32
comment                        int16
dtype: object

In [9]:
donnees.to_parquet('./ecommerce/reviews.parquet',compression='gzip', engine='pyarrow')

## Sauvegarde dans la base de données

In [10]:
donnees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   review_id           100000 non-null  object
 1   order_id            100000 non-null  object
 2   score               100000 non-null  int16
 3   comment_title       11715 non-null   object
 4   comment_message     41753 non-null   object
 5   creation_date       100000 non-null  datetime64[ns]
 6   answer_timestamp    100000 non-null  datetime64[ns]
 7   purchase_timestamp  100000 non-null  datetime64[ns]
 8   creation            100000 non-null  int32
 9   answer              100000 non-null  int32
 10  comment             100000 non-null  int16
dtypes: datetime64[ns](3), int16(2), int32(2), object(4)
memory usage: 6.5+ MB

In [11]:
donnees.to_sql('reviews',
               # schema='ebrasil',
               con=connection,
               if_exists='replace',
               index=False,
               dtype={ 
                        "review_id"          :sqlalchemy.types.String(80),       
                        "order_id"           :sqlalchemy.types.String(80),        
                        "score"              :sqlalchemy.types.Integer(),         
                        "comment_title"      :sqlalchemy.types.String(80),        
                        "comment_message"    :sqlalchemy.types.String(256),     
                        "creation_date"      :sqlalchemy.types.DateTime(),
                        "answer_timestamp"   :sqlalchemy.types.DateTime(),
                        "purchase_timestamp" :sqlalchemy.types.DateTime(),
                        "creation"           :sqlalchemy.types.Integer(),         
                        "answer"             :sqlalchemy.types.Integer(),         
                        "comment"            :sqlalchemy.types.Integer()
               })

1000

In [12]:
requete  = "select count(*) from reviews"
pd.read_sql_query(requete, connection)

    count
0  100000

## Transformation de la table

In [13]:
donnees.pivot_table(index='order_id',
                    columns='score',
                    values=['review_id','creation','answer','comment'], 
                    aggfunc={'review_id':'count','creation':'sum','answer':'sum','comment':'sum'},
                    fill_value=0)

                                 answer               comment               \
score                                 1  2  3   4   5       1  2  3  4   5
order_id
00010242fe8c5a6d1ba2dd792cb16214      0  0  0   0  34       0  0  0  0  46
00018f77f2f0320c557190d7a144bdd3      0  0  0  59   0       0  0  0  3   0
000229ec398224ef6ca0657da4fc703e      0  0  0   0  16       0  0  0  0  90
00024acbcdf0a6daa1e931b038114c75      0  0  0  16   0       0  0  0  3   0
00042b26cf59d7ce69dfabb4e55b4fd9      0  0  0   0  34       0  0  0  0  39
...                                 ... .. ..  ..  ..     ... .. .. ..  ..
fffc94f6ce00a00581880bf54a75a037      0  0  0   0  84       0  0  0  0   3
fffcd46ef2263f404302a634eb57f7eb      0  0  0   0  33       0  0  0  0   3
fffce4705a9662cd70adb13d4a31832d      0  0  0   0  21       0  0  0  0   3
fffe18544ffabc95dfada21779c9644f      0  0  0   0  36       0  0  0  0  47
fffe41c64501cc87c801fd61db3f6244      0  0  0   0  69       0  0  0  0   3

                                 creation                 review_id           \
score                                   1  2  3    4    5         1  2  3  4
order_id
00010242fe8c5a6d1ba2dd792cb16214        0  0  0    0  183         0  0  0  0
00018f77f2f0320c557190d7a144bdd3        0  0  0  397    0         0  0  0  1
000229ec398224ef6ca0657da4fc703e        0  0  0    0  201         0  0  0  0
00024acbcdf0a6daa1e931b038114c75        0  0  0  157    0         0  0  0  1
00042b26cf59d7ce69dfabb4e55b4fd9        0  0  0    0  610         0  0  0  0
...                                   ... .. ..  ...  ...       ... .. .. ..
fffc94f6ce00a00581880bf54a75a037        0  0  0    0  418         0  0  0  0
fffcd46ef2263f404302a634eb57f7eb        0  0  0    0  229         0  0  0  0
fffce4705a9662cd70adb13d4a31832d        0  0  0    0  126         0  0  0  0
fffe18544ffabc95dfada21779c9644f        0  0  0    0   48         0  0  0  0
fffe41c64501cc87c801fd61db3f6244        0  0  0    0  126         0  0  0  0


score                             5
order_id
00010242fe8c5a6d1ba2dd792cb16214  1
00018f77f2f0320c557190d7a144bdd3  0
000229ec398224ef6ca0657da4fc703e  1
00024acbcdf0a6daa1e931b038114c75  0
00042b26cf59d7ce69dfabb4e55b4fd9  1
...                              ..
fffc94f6ce00a00581880bf54a75a037  1
fffcd46ef2263f404302a634eb57f7eb  1
fffce4705a9662cd70adb13d4a31832d  1
fffe18544ffabc95dfada21779c9644f  1
fffe41c64501cc87c801fd61db3f6244  1

[99441 rows x 20 columns]

In [14]:
donnees = donnees.pivot_table(index='order_id',
                    columns='score',
                    values=['review_id','creation','answer','comment'], 
                    aggfunc={'review_id':'count','creation':'sum','answer':'sum','comment':'sum'},
                    fill_value=0)
donnees.columns = [f"{col[0].replace('review_id','score')}_{col[1]}" for col in donnees.columns]
donnees.reset_index(inplace=True)
donnees['score'] = donnees.score_1+\
                   donnees.score_2+\
                   donnees.score_3+\
                   donnees.score_4+\
                   donnees.score_5

donnees['answer'] = donnees.answer_1+\
                   donnees.answer_2+\
                   donnees.answer_3+\
                   donnees.answer_4+\
                   donnees.answer_5

donnees['creation'] = donnees.creation_1+\
                      donnees.creation_2+\
                      donnees.creation_3+\
                      donnees.creation_4+\
                      donnees.creation_5

donnees['comment'] = donnees.comment_1+\
                   donnees.comment_2+\
                   donnees.comment_3+\
                   donnees.comment_4+\
                   donnees.comment_5
donnees.head()

,order_id,answer_1,answer_2,answer_3,answer_4,answer_5,comment_1,comment_2,comment_3,comment_4,...,creation_5,score_1,score_2,score_3,score_4,score_5,score,answer,creation,comment
0,00010242fe8c5a6d1ba2dd792cb16214,0,0,0,0,34,0,0,0,0,...,183,0,0,0,0,1,1,34,183,46
1,00018f77f2f0320c557190d7a144bdd3,0,0,0,59,0,0,0,0,3,...,0,0,0,0,1,0,1,59,397,3
2,000229ec398224ef6ca0657da4fc703e,0,0,0,0,16,0,0,0,0,...,201,0,0,0,0,1,1,16,201,90
3,00024acbcdf0a6daa1e931b038114c75,0,0,0,16,0,0,0,0,3,...,0,0,0,0,1,0,1,16,157,3
4,00042b26cf59d7ce69dfabb4e55b4fd9,0,0,0,0,34,0,0,0,0,...,610,0,0,0,0,1,1,34,610,39

In [15]:
donnees.to_parquet('./ecommerce/reviews_p.parquet',compression='gzip', engine='pyarrow')

In [16]:
!dir ecommerce

 Le volume dans le lecteur C s'appelle Windows
 Le num‚ro de s‚rie du volume est 7E56-F105

 R‚pertoire de C:\dev\PythonFormation\donnees\ecommerce

23/09/2026  15:33    <DIR>          .
04/06/2026  10:58    <DIR>          ..
23/09/2026  15:55         4ÿ513ÿ352 customers.parquet
09/10/2025  10:23        14ÿ319ÿ809 etoile01.parquet
09/10/2025  15:54        17ÿ371ÿ074 etoile02.parquet
09/10/2025  10:32        18ÿ160ÿ225 etoile03.parquet
23/09/2026  16:21         1ÿ118ÿ998 geolocation.parquet
23/09/2026  15:25         4ÿ803ÿ098 items.parquet
23/09/2026  15:09         9ÿ538ÿ920 orders.parquet
23/09/2026  15:29         9ÿ991ÿ736 orders_payments.parquet
23/09/2026  15:29        13ÿ250ÿ586 orders_payments_items.parquet
23/09/2026  15:27         2ÿ648ÿ862 payments.parquet
23/09/2026  15:27         2ÿ464ÿ323 paymentsI.parquet
23/09/2026  15:51           959ÿ732 products.parquet
23/09/2026  16:47         7ÿ520ÿ329 reviews.parquet
23/09/2026  16:47         2ÿ829ÿ017 reviews_p.parquet
23/09/2026  15:59            91ÿ207 sellers.parquet
07/10/2025  17:33        13ÿ726ÿ242 tp08.agregat.parquet
07/10/2025  17:33        18ÿ160ÿ225 tp08.complet.parquet
09/10/2025  12:13           377ÿ286 Ventes.Regions.html
              18 fichier(s)      141ÿ845ÿ021 octets
               2 R‚p(s)  155ÿ003ÿ432ÿ960 octets libres

## Sauvegarde dans la base de données

In [17]:
donnees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 25 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    99441 non-null  object
 1   answer_1    99441 non-null  int32
 2   answer_2    99441 non-null  int32
 3   answer_3    99441 non-null  int32
 4   answer_4    99441 non-null  int32
 5   answer_5    99441 non-null  int32
 6   comment_1   99441 non-null  int16
 7   comment_2   99441 non-null  int16
 8   comment_3   99441 non-null  int16
 9   comment_4   99441 non-null  int16
 10  comment_5   99441 non-null  int16
 11  creation_1  99441 non-null  int32
 12  creation_2  99441 non-null  int32
 13  creation_3  99441 non-null  int32
 14  creation_4  99441 non-null  int32
 15  creation_5  99441 non-null  int32
 16  score_1     99441 non-null  int64
 17  score_2     99441 non-null  int64
 18  score_3     99441 non-null  int64
 19  score_4     99441 non-null  int64
 20  score_5     99441 non-null  int64
 21  score       99441 non-null  int64
 22  answer      99441 non-null  int32
 23  creation    99441 non-null  int32
 24  comment     99441 non-null  int16
dtypes: int16(6), int32(12), int64(6), object(1)
memory usage: 11.0+ MB

In [21]:
engine = sqlalchemy.create_engine("postgresql://formation:formation@localhost:5432/ebrasil")
connection = engine.connect()
print("connecting with engine " + str(engine))

connecting with engine Engine(postgresql://formation:***@localhost:5432/ebrasil)

In [22]:
donnees.to_sql('reviews_p',
               # schema='ebrasil',
               con=connection,
               if_exists='replace',
               index=False,
               dtype={ 
                        "order_id"   :sqlalchemy.types.String(80),
                        "answer_1"   :sqlalchemy.types.Integer(),
                        "answer_2"   :sqlalchemy.types.Integer(),
                        "answer_3"   :sqlalchemy.types.Integer(),
                        "answer_4"   :sqlalchemy.types.Integer(),
                        "answer_5"   :sqlalchemy.types.Integer(),
                        "comment_1"  :sqlalchemy.types.Integer(),
                        "comment_2"  :sqlalchemy.types.Integer(),
                        "comment_3"  :sqlalchemy.types.Integer(),
                        "comment_4"  :sqlalchemy.types.Integer(),
                        "comment_5"  :sqlalchemy.types.Integer(),
                        "creation_1" :sqlalchemy.types.Integer(),
                        "creation_2" :sqlalchemy.types.Integer(),
                        "creation_3" :sqlalchemy.types.Integer(),
                        "creation_4" :sqlalchemy.types.Integer(),
                        "creation_5" :sqlalchemy.types.Integer(),
                        "score_1"    :sqlalchemy.types.Integer(),
                        "score_2"    :sqlalchemy.types.Integer(),
                        "score_3"    :sqlalchemy.types.Integer(),
                        "score_4"    :sqlalchemy.types.Integer(),
                        "score_5"    :sqlalchemy.types.Integer(),
                        "score"      :sqlalchemy.types.Integer(),
                        "answer"     :sqlalchemy.types.Integer(),
                        "creation"   :sqlalchemy.types.Integer(),
                        "comment"    :sqlalchemy.types.Integer()
               })

441

In [23]:
requete  = "select count(*) from reviews_p"
pd.read_sql_query(requete, connection)

   count
0  99441