<img src="https://raw.githubusercontent.com/rbizoi/PythonFormation/main/images/e-brasil.png" width="850">

# Les imports et initialisations des variables

In [1]:
from datetime import datetime
import pandas as pd, numpy as np, os, warnings, seaborn as sns, pickle, re, unicodedata
from datetime import datetime as dt
import sqlalchemy

warnings.filterwarnings(action="ignore")

engine = sqlalchemy.create_engine("postgresql://formation:formation@localhost:5432/ebrasil")
connection = engine.connect()
print("connecting with engine " + str(engine))

connecting with engine Engine(postgresql://formation:***@localhost:5432/ebrasil)

## Liste fichiers de données

In [2]:
!dir ..\donnees\ebrasil

 Le volume dans le lecteur C s'appelle Windows
 Le num‚ro de s‚rie du volume est 7E56-F105

 R‚pertoire de C:\dev\PythonFormation\donnees\ebrasil

10/01/2024  11:34    <DIR>          .
04/06/2026  10:58    <DIR>          ..
06/10/2019  21:27         9ÿ033ÿ957 olist_customers_dataset.csv
06/10/2019  21:27        61ÿ273ÿ883 olist_geolocation_dataset.csv
06/10/2019  21:27        17ÿ654ÿ914 olist_orders_dataset.csv
06/10/2019  21:27        15ÿ438ÿ671 olist_order_items_dataset.csv
06/10/2019  21:27         5ÿ777ÿ138 olist_order_payments_dataset.csv
06/10/2019  21:27        14ÿ409ÿ007 olist_order_reviews_dataset.csv
06/10/2019  21:27         2ÿ379ÿ446 olist_products_dataset.csv
28/09/2020  08:52           177ÿ799 olist_sellers_dataset.csv
10/01/2024  11:19             2ÿ613 product_category_name_translation.csv
               9 fichier(s)      126ÿ147ÿ428 octets
               2 R‚p(s)  154ÿ995ÿ036ÿ160 octets libres

## Changement de répertoire

In [3]:
os.chdir(r"../donnees")

# DataFrame $customers$

In [4]:
donnees = pd.read_csv(os.path.join('ebrasil', 'olist_customers_dataset.csv'))

In [5]:
dictEtats = {'AC':'Acre',              
             'AL':'Alagoas',
             'AP':'Amapá',
             'AM':'Amazonas',
             'BA':'Bahia',
             'CE':'Ceará',
             'ES':'Espírito Santo',
             'GO':'Goiás',
             'MA':'Maranhão',
             'MT':'Mato Grosso',
             'MS':'Mato Grosso do Sul', 
             'MG':'Minas Gerais',
             'PA':'Pará',
             'PB':'Paraïba',
             'PR':'Paraná',
             'PE':'Pernambouc',
             'PI':'Piauí',
             'RJ':'Rio de Janeiro',
             'RN':'Rio Grande do Norte',  
             'RS':'Rio Grande do Sul',
             'RO':'Rondônia',
             'RR':'Roraima',
             'SC':'Santa Catarina',
             'SP':'São Paulo',
             'SE':'Sergipe',
             'TO':'Tocantins',
             'DF':'District fédéral'} 
donnees['name_state'] = donnees['customer_state'].apply(lambda x : dictEtats[x])
donnees['customer_zip_code_prefix'] = donnees['customer_zip_code_prefix'].astype('int32')
donnees.rename(columns={'customer_zip_code_prefix':'zip_code','customer_city':'city','customer_state':'state'},inplace=True)

In [6]:
donnees.head()

,customer_id,customer_unique_id,zip_code,city,state,name_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,São Paulo
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,São Paulo
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,São Paulo
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,São Paulo
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,São Paulo

In [7]:
donnees.dtypes

customer_id           object
customer_unique_id    object
zip_code               int32
city                  object
state                 object
name_state            object
dtype: object

In [8]:
donnees.isna().sum()

customer_id           0
customer_unique_id    0
zip_code              0
city                  0
state                 0
name_state            0
dtype: int64

In [9]:
donnees.shape[0],donnees.customer_id.nunique(), donnees.customer_unique_id.nunique()

(99441, 99441, 96096)

In [10]:
donnees.head()

,customer_id,customer_unique_id,zip_code,city,state,name_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,São Paulo
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,São Paulo
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,São Paulo
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,São Paulo
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,São Paulo

## Sauvegarde en parquet

In [11]:
donnees.to_parquet('./ecommerce/customers.parquet',compression='gzip', engine='pyarrow')

In [12]:
pd.read_parquet('./ecommerce/customers.parquet').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         99441 non-null  object
 1   customer_unique_id  99441 non-null  object
 2   zip_code            99441 non-null  int32
 3   city                99441 non-null  object
 4   state               99441 non-null  object
 5   name_state          99441 non-null  object
dtypes: int32(1), object(5)
memory usage: 4.2+ MB

In [13]:
!dir ecommerce

 Le volume dans le lecteur C s'appelle Windows
 Le num‚ro de s‚rie du volume est 7E56-F105

 R‚pertoire de C:\dev\PythonFormation\donnees\ecommerce

23/09/2026  15:33    <DIR>          .
04/06/2026  10:58    <DIR>          ..
23/09/2026  15:55         4ÿ513ÿ352 customers.parquet
09/10/2025  10:23        14ÿ319ÿ809 etoile01.parquet
09/10/2025  15:54        17ÿ371ÿ074 etoile02.parquet
09/10/2025  10:32        18ÿ160ÿ225 etoile03.parquet
07/10/2025  16:19         1ÿ121ÿ951 geolocation.parquet
23/09/2026  15:25         4ÿ803ÿ098 items.parquet
23/09/2026  15:09         9ÿ538ÿ920 orders.parquet
23/09/2026  15:29         9ÿ991ÿ736 orders_payments.parquet
23/09/2026  15:29        13ÿ250ÿ586 orders_payments_items.parquet
23/09/2026  15:27         2ÿ648ÿ862 payments.parquet
23/09/2026  15:27         2ÿ464ÿ323 paymentsI.parquet
23/09/2026  15:51           959ÿ732 products.parquet
23/09/2026  15:47         7ÿ520ÿ329 reviews.parquet
23/09/2026  15:47         2ÿ829ÿ017 reviews_p.parquet
07/10/2025  16:19            91ÿ402 sellers.parquet
07/10/2025  17:33        13ÿ726ÿ242 tp08.agregat.parquet
07/10/2025  17:33        18ÿ160ÿ225 tp08.complet.parquet
09/10/2025  12:13           377ÿ286 Ventes.Regions.html
              18 fichier(s)      141ÿ848ÿ169 octets
               2 R‚p(s)  154ÿ995ÿ032ÿ064 octets libres

## Sauvegarde dans la base de données

In [14]:
donnees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         99441 non-null  object
 1   customer_unique_id  99441 non-null  object
 2   zip_code            99441 non-null  int32
 3   city                99441 non-null  object
 4   state               99441 non-null  object
 5   name_state          99441 non-null  object
dtypes: int32(1), object(5)
memory usage: 4.2+ MB

In [15]:
donnees.to_sql('customers',
               # schema='ebrasil',
               con=connection,
               if_exists='replace',
               index=False,
               dtype={ 
                        "customer_id"        :sqlalchemy.types.String(80),
                        "customer_unique_id" :sqlalchemy.types.String(80),
                        "zip_code"           :sqlalchemy.types.Integer(),
                        "city"               :sqlalchemy.types.String(80),
                        "state"              :sqlalchemy.types.String(80),
                        "name_state"         :sqlalchemy.types.String(80)
               })

441

In [16]:
requete  = "select count(*) from customers"
pd.read_sql_query(requete, connection)

   count
0  99441