<img src="https://raw.githubusercontent.com/rbizoi/PythonFormation/main/images/e-brasil.png" width="850">

# Les imports et initialisations des variables

In [1]:
from datetime import datetime
import pandas as pd, numpy as np, os, warnings, seaborn as sns, pickle, re, unicodedata
from datetime import datetime as dt
import sqlalchemy

warnings.filterwarnings(action="ignore")

engine = sqlalchemy.create_engine("postgresql://formation:formation@localhost:5432/ebrasil")
connection = engine.connect()
print("connecting with engine " + str(engine))

connecting with engine Engine(postgresql://formation:***@localhost:5432/ebrasil)

## Liste fichiers de données

In [2]:
!dir ..\donnees\ebrasil

 Le volume dans le lecteur C s'appelle Windows
 Le num‚ro de s‚rie du volume est 7E56-F105

 R‚pertoire de C:\dev\PythonFormation\donnees\ebrasil

10/01/2024  11:34    <DIR>          .
04/06/2026  10:58    <DIR>          ..
06/10/2019  21:27         9ÿ033ÿ957 olist_customers_dataset.csv
06/10/2019  21:27        61ÿ273ÿ883 olist_geolocation_dataset.csv
06/10/2019  21:27        17ÿ654ÿ914 olist_orders_dataset.csv
06/10/2019  21:27        15ÿ438ÿ671 olist_order_items_dataset.csv
06/10/2019  21:27         5ÿ777ÿ138 olist_order_payments_dataset.csv
06/10/2019  21:27        14ÿ409ÿ007 olist_order_reviews_dataset.csv
06/10/2019  21:27         2ÿ379ÿ446 olist_products_dataset.csv
28/09/2020  08:52           177ÿ799 olist_sellers_dataset.csv
10/01/2024  11:19             2ÿ613 product_category_name_translation.csv
               9 fichier(s)      126ÿ147ÿ428 octets
               2 R‚p(s)  155ÿ008ÿ815ÿ104 octets libres

## Changement de répertoire

In [3]:
os.chdir(r"../donnees")

## Fonctions utilitaires

In [4]:
def nettoyer(valeur):
    nk = unicodedata.normalize('NFKD', valeur.lower())
    valeur = str(nk.encode('ASCII', 'ignore').decode('ASCII'))
    return re.compile('[^\w ]').sub('', valeur).strip().replace('  ',' ')

# DataFrame $items$

In [5]:
donnees = pd.read_csv(os.path.join('ebrasil', 'olist_geolocation_dataset.csv'))
donnees.rename(columns={col:col.replace('geolocation_','').replace('_prefix','') for col in donnees.columns},inplace=True)
dictEtats = {'AC':'Acre',              
             'AL':'Alagoas',
             'AP':'Amapá',
             'AM':'Amazonas',
             'BA':'Bahia',
             'CE':'Ceará',
             'ES':'Espírito Santo',
             'GO':'Goiás',
             'MA':'Maranhão',
             'MT':'Mato Grosso',
             'MS':'Mato Grosso do Sul', 
             'MG':'Minas Gerais',
             'PA':'Pará',
             'PB':'Paraïba',
             'PR':'Paraná',
             'PE':'Pernambouc',
             'PI':'Piauí',
             'RJ':'Rio de Janeiro',
             'RN':'Rio Grande do Norte',  
             'RS':'Rio Grande do Sul',
             'RO':'Rondônia',
             'RR':'Roraima',
             'SC':'Santa Catarina',
             'SP':'São Paulo',
             'SE':'Sergipe',
             'TO':'Tocantins',
             'DF':'District fédéral'} 
donnees['state'] = donnees['state'].apply(lambda x : dictEtats[x])
donnees['zip_code'] = donnees['zip_code'].astype('int32')

In [6]:
donnees.columns

Index(['zip_code', 'lat', 'lng', 'city', 'state'], dtype='object')

In [7]:
donnees.head()

   zip_code        lat        lng       city      state
0      1037 -23.545621 -46.639292  sao paulo  São Paulo
1      1046 -23.546081 -46.644820  sao paulo  São Paulo
2      1046 -23.546129 -46.642951  sao paulo  São Paulo
3      1041 -23.544392 -46.639499  sao paulo  São Paulo
4      1035 -23.541578 -46.641607  sao paulo  São Paulo

In [8]:
donnees.dtypes

zip_code      int32
lat         float64
lng         float64
city         object
state        object
dtype: object

In [9]:
clients = pd.read_parquet('./ecommerce/customers.parquet')
clients.zip_code.nunique()

14994

In [10]:
vendeurs = pd.read_parquet('./ecommerce/sellers.parquet')
vendeurs.zip_code.nunique()

2246

In [11]:
donnees.columns,clients.columns,vendeurs.columns

(Index(['zip_code', 'lat', 'lng', 'city', 'state'], dtype='object'),
 Index(['customer_id', 'customer_unique_id', 'zip_code', 'city', 'state',
        'name_state'],
       dtype='object'),
 Index(['seller_id', 'zip_code', 'city', 'state', 'name_state'], dtype='object'))

In [12]:
donnees.merge(clients,on='zip_code',how='left').zip_code.nunique(),\
donnees.merge(clients,on='zip_code',how='right').zip_code.nunique()

(19015, 14994)

In [13]:
donnees.merge(vendeurs,on='zip_code',how='left').zip_code.nunique(),\
donnees.merge(vendeurs,on='zip_code',how='right').zip_code.nunique()

(19015, 2246)

In [14]:
donnees.shape

(1000163, 5)

In [15]:
donnees.zip_code.nunique()

19015

In [16]:
donnees[['zip_code','city','state']].drop_duplicates().shape

(27912, 3)

In [17]:
list(donnees.city.sort_values().unique())

['* cidade',
 '...arraial do cabo',
 '4o. centenario',
 '4º centenario',
 'abadia de goias',
 'abadia dos dourados',
 'abadiania',
 'abadiânia',
 'abaete',
 'abaetetuba',
 'abaeté',
 'abaiara',
 'abaira',
 'abare',
 'abaré',
 'abatia',
 'abatiá',
 'abaíra',
 'abdon batista',
 'abel figueiredo',
 'abelardo luz',
 'abrantes',
 'abre campo',
 'abreu e lima',
 'abreulândia',
 'abreus',
 'acaiaca',
 'acailandia',
 'acajutiba',
 'acara',
 'acarape',
 'acarau',
 'acaraú',
 'acari',
 'acará',
 'acaua',
 'acauã',
 'acegua',
 'aceguá',
 'acioli',
 'acopiara',
 'acorizal',
 'acrelandia',
 'acrelândia',
 'acreuna',
 'acreúna',
 'acu',
 'acucena',
 'acupe',
 'adamantina',
 'adao colares',
 'adelandia',
 'adhemar de barros',
 'adolfo',
 'adrianopolis',
 'adrianópolis',
 'adustina',
 'afogados da ingazeira',
 'afonso arinos',
 'afonso bezerra',
 'afonso claudio',
 'afonso cláudio',
 'afonso cunha',
 'afranio',
 'afrânio',
 'afua',
 'afuá',
 'agisse',
 'agrestina',
 'agricolandia',
 'agricolândia',
 'agrolandia',
 'agrolândia',
 'agronomica',
 'agronômica',
 'agua azul do norte',
 'agua boa',
 'agua branca',
 'agua branca de minas',
 'agua clara',
 'agua comprida',
 'agua doce',
 'agua doce do maranhao',
 'agua doce do norte',
 'agua fria',
 'agua fria de goias',
 'agua limpa',
 'agua nova',
 'agua preta',
 'agua santa',
 'agua vermelha',
 'aguai',
 'aguanil',
 'aguas belas',
 'aguas claras',
 'aguas da prata',
 'aguas de chapeco',
 'aguas de lindoia',
 'aguas de santa barbara',
 'aguas de sao pedro',
 'aguas ferreas',
 'aguas formosas',
 'aguas frias',
 'aguas lindas de goias',
 'aguas mornas',
 'aguas vermelhas',
 'aguaí',
 'agudo',
 'agudos',
 'agudos do sul',
 'aguia branca',
 'aguiar',
 'aguiarnopolis',
 'aguiarnópolis',
 'agulha',
 'aimores',
 'aimorés',
 'aiquara',
 'aiuaba',
 'aiuruoca',
 'ajuricaba',
 'alagoa',
 'alagoa grande',
 'alagoa nova',
 'alagoinha',
 'alagoinha do piaui',
 'alagoinha do piauí',
 'alagoinhas',
 'alambari',
 'albertina',
 'alberto isaacson',
 'alcantara',
 'alcantaras',
 'alcantil',
 'alcinopolis',
 'alcinópolis',
 'alcobaca',
 'alcobaça',
 'alcântara',
 'alcântaras',
 'aldeia',
 'aldeias altas',
 'alecrim',
 'alegre',
 'alegrete',
 'alegrete do piaui',
 'alegrete do piauí',
 'alegria',
 'alem paraiba',
 'alenquer',
 'alexandra',
 'alexandria',
 'alexandrita',
 'alexania',
 'alexânia',
 'alfenas',
 'alfredo chaves',
 'alfredo guedes',
 'alfredo marcondes',
 'alfredo vasconcelos',
 'alfredo wagner',
 'algodão de jandaíra',
 'algodões',
 'alhandra',
 'alianca',
 'alianca do tocantins',
 'aliança',
 'aliança do tocantins',
 'almadina',
 'almas',
 'almeirim',
 'almenara',
 'almino afonso',
 'almirante tamandare',
 'almirante tamandare do sul',
 'almirante tamandaré',
 'almirante tamandaré do sul',
 'aloandia',
 'aloândia',
 'alpercata',
 'alpestre',
 'alpinopolis',
 'alpinópolis',
 'alta alegre dos parecis',
 'alta floresta',
 "alta floresta d'oeste",
 'alta floresta do oeste',
 'alta floresta doeste',
 'altair',
 'altamira',
 'altamira do maranhao',
 'altamira do parana',
 'altamira do paraná',
 'altaneira',
 'alterosa',
 'altinho',
 'altinopolis',
 'altinópolis',
 'alto alegre',
 'alto alegre do iguacu',
 'alto alegre do maranhao',
 'alto alegre do pindare',
 'alto alegre do pindaré',
 'alto alegre dos parecis',
 'alto araguaia',
 'alto bela vista',
 'alto boa vista',
 'alto calcado',
 'alto caparao',
 'alto caparaó',
 'alto do rodrigues',
 'alto feliz',
 'alto garcas',
 'alto garças',
 'alto horizonte',
 'alto jequitiba',
 'alto jequitibá',
 'alto longa',
 'alto maranhao',
 'alto mutum preto',
 'alto paraguai',
 'alto paraiso',
 'alto paraiso de goias',
 'alto parana',
 'alto paraná',
 'alto paraíso',
 'alto paraíso de goiás',
 'alto parnaiba',
 'alto parnaíba',
 'alto piquiri',
 'alto rio doce',
 'alto rio novo',
 'alto santo',
 'alto taquari',
 'altonia',
 'altos',
 'altônia',
 'aluminio',
 'alumínio',
 'alvacao',
 'alvaraes',
 'alvarenga',
 'alvares florence',
 'alvares machado',
 'alvaro de carvalho',
 'alvinlandia',
 'alvinlândia',
 'alvinopolis',
 'alvinópolis',
 'alvorada',
 "alvorada d'oeste",
 'alvorada de minas',
 'alvorada do gurgueia',
 'alvorada do gurguéia',
 'alvorada do norte',
 'alvorada do oeste',
 'alvorada do sul',
 'além paraíba',
 'amambai',
 'amambaí',
 'amanari',
 'amandina',
 'amanhece',
 'amapa',
 'amapa do maranhao',
 'amapari',
 'amapora',
 'amaporã',
 'amapá do maranhão',
 'amaraji',
 'amaral ferrador',
 'amaralina',
 'amarante',
 'amarante do maranhao',
 'amarantina',
 'amargosa',
 'amatura',
 'amaturá',
 'amelia rodrigues',
 'america dourada',
 'americana',
 'americano',
 'americano do brasil',
 'americo brasiliense',
 'americo de campos',
 'ametista do sul',
 'amontada',
 'amorinopolis',
 'amorinópolis',
 'amparo',
 'amparo da serra',
 'amparo de sao francisco',
 'ampere',
 'ampére',
 'amélia rodrigues',
 'américo brasiliense',
 'américo de campos',
 'ana dias',
 'anadia',
 'anage',
 'anagé',
 'anahy',
 'anajas',
 'anajatuba',
 'anajás',
 'analandia',
 'anama',
 'ananas',
 'ananindeua',
 'ananás',
 'anapolis',
 'anapu',
 'anapurus',
 'anastacio',
 'anastácio',
 'anaurilandia',
 'anaurilândia',
 'anchieta',
 'andarai',
 'andaraí',
 'andira',
 'andirá',
 'andorinha',
 'andradas',
 'andrade pinto',
 'andradina',
 'andre da rocha',
 'andrelandia',
 'andrelândia',
 'andrequice',
 'andré da rocha',
 'angatuba',
 'angelandia',
 'angelica',
 'angelim',
 'angelina',
 'angelândia',
 'angical',
 'angical do piaui',
 'angical do piauí',
 'angico',
 'angicos',
 'angra dos reis',
 'anguera',
 'anguereta',
 'angulo',
 'angustura',
 'angélica',
 'anhandui',
 'anhanguera',
 'anhembi',
 'anhumas',
 'anicuns',
 'anisio de abreu',
 'anita garibaldi',
 'anitapolis',
 'anitápolis',
 'anori',
 'anta',
 'anta gorda',
 'antas',
 'antonina',
 'antonina do norte',
 'antonio almeida',
 'antonio cardoso',
 'antonio carlos',
 'antonio dias',
 'antonio goncalves',
 'antonio joao',
 'antonio martins',
 'antonio olinto',
 'antonio pereira',
 'antonio prado',
 'antonio prado de minas',
 'antunes',
 'antunes (igaratinga)',
 'antônio almeida',
 'antônio cardoso',
 'antônio carlos',
 'antônio dias',
 'antônio gonçalves',
 'antônio joão',
 'antônio martins',
 'antônio olinto',
 'antônio pereira',
 'antônio prado',
 'antônio prado de minas',
 'anápolis',
 'aparecida',
 'aparecida d oeste',
 "aparecida d'oeste",
 'aparecida de goiania',
 'aparecida de goiânia',
 'aparecida de minas',
 'aparecida de monte alto',
 'aparecida de sao manuel',
 'aparecida de são manuel',
 'aparecida do rio doce',
 'aparecida do rio negro',
 'aparecida do taboado',
 'aparecida doeste',
 'aperibe',
 'aperibé',
 'apeu',
 'apiaca',
 'apiacas',
 'apiacá',
 'apiacás',
 'apiai',
 'apiaí',
 'apicum-acu',
 'apiuna',
 'apiúna',
 'apodi',
 'apora',
 'apore',
 'aporá',
 'aporé',
 'apuarema',
 'apucarana',
 'apui',
 'apuiares',
 'apuiarés',
 'apuí',
 'aquidaba',
 'aquidaban',
 'aquidabã',
 'aquidauana',
 'aquiraz',
 'arabuta',
 'aracagi',
 'aracai',
 'aracaju',
 'aracariguama',
 'aracas',
 'aracati',
 'aracatu',
 'aracatuba',
 'arace',
 'araci',
 'aracitaba',
 'aracoiaba',
 'aracoiaba da serra',
 'aracruz',
 'aracu',
 'aracuai',
 'aragarcas',
 'aragarças',
 'aragoiania',
 'aragoiânia',
 'aragominas',
 'araguacema',
 'araguacu',
 'araguaia',
 'araguaiana',
 'araguaina',
 'araguainha',
 'araguana',
 'araguanã',
 'araguapaz',
 'araguari',
 'araguatins',
 'araguaçu',
 'araguaína',
 'araioses',
 'araióses',
 'aral moreira',
 'aramari',
 'arambare',
 'arambaré',
 'arame',
 'aramina',
 'arandu',
 'arantina',
 'arapei',
 'arapeí',
 'arapiraca',
 'arapoema',
 'araponga',
 'arapongas',
 'arapora',
 'araporã',
 'arapoti',
 'arapua',
 'araputanga',
 'arapuá',
 'arapuã',
 'araquari',
 'arara',
 'ararangua',
 'araranguá',
 'araraquara',
 'araras',
 'ararenda',
 'ararendá',
 'arari',
 'ararica',
 'araricá',
 'araripe',
 'araripina',
 'araruama',
 'araruna',
 'arataca',
 'aratiba',
 'aratuba',
 'aratuipe',
 'aratuípe',
 'araua',
 'araucaria',
 'araucária',
 'araujos',
 'arauá',
 'araxa',
 'araxá',
 'araçagi',
 'araçariguama',
 'araçatuba',
 'araçaí',
 'araçoiaba',
 'araçoiaba da serra',
 'araçu',
 'araçuaí',
 'araçás',
 'araújos',
 'arceburgo',
 'arco verde',
 'arco-iris',
 'arcos',
 'arcoverde',
 'areado',
 'areal',
 'arealva',
 'areia',
 'areia branca',
 'areia branca dos assis',
 'areia de baraunas',
 'areial',
 'areias',
 'areiopolis',
 'areiópolis',
 'arembepe',
 'arenapolis',
 'arenopolis',
 'arenápolis',
 'arez',
 'argirita',
 'aricanduva',
 'arinos',
 'aripuana',
 'aripuanã',
 'ariquemes',
 'ariranha',
 'ariranha do ivai',
 'ariranha do ivaí',
 'armacao de buzios',
 'armacao dos buzios',
 'armazem',
 'armazém',
 'armação dos búzios',
 'arneiroz',
 'aroazes',
 'aroeiras',
 'arraial',
 'arraial d ajuda',
 "arraial d'ajuda",
 'arraial do cabo',
 'arraias',
 'arroio do meio',
 'arroio do padre',
 'arroio do sal',
 'arroio do tigre',
 'arroio dos ratos',
 'arroio grande',
 'arroio trinta',
 'arrozal',
 'artur nogueira',
 'aruana',
 'aruanã',
 'aruja',
 'arujá',
 'arvoredo',
 'arvorezinha',
 'ascurra',
 'aspasia',
 'aspásia',
 'assai',
 'assare',
 'assaré',
 'assaí',
 'assis',
 'assis brasil',
 'assis chateaubriand',
 'assuncao',
 'assuncao do piaui',
 'astolfo dutra',
 'astorga',
 'atalaia',
 'atalaia do norte',
 'atalanta',
 'ataleia',
 'ataléia',
 'atibaia',
 'atilio vivacqua',
 'augustinopolis',
 'augustinópolis',
 'augusto correa',
 'augusto corrêa',
 'augusto de lima',
 'augusto pestana',
 'aurea',
 'aurelino leal',
 'auriflama',
 'aurilandia',
 'aurora',
 'aurora do iguacu',
 'aurora do para',
 'aurora do tocantins',
 'autazes',
 'avai',
 'avanhandava',
 'avare',
 'avaré',
 'avaí',
 'avaí do jacinto',
 'avelar',
 'avelino lopes',
 'avelinopolis',
 'axixa',
 'axixa do tocantins',
 'axixá do tocantins',
 'azambuja',
 'azurita',
 'açailândia',
 'açu',
 'açu da torre',
 'açucena',
 'babaculandia',
 'bacabal',
 'bacabeira',
 'bacaxa',
 'bacaxa (saquarema) - distrito',
 'bacuri',
 'bacurituba',
 'bady bassitt',
 'baependi',
 'bage',
 'bagre',
 'baguacu',
 'baguari',
 'bagé',
 'baia formosa',
 'baianopolis',
 'baiao',
 'baixa grande',
 'baixa grande do ribeiro',
 'baixio',
 'baixo guandu',
 'baião',
 'balbinos',
 'baldim',
 'baliza',
 'balneario arroio do silva',
 'balneario barra do sul',
 'balneario camboriu',
 'balneario de picarras',
 'balneario gaivota',
 'balneario picarras',
 'balneario pinhal',
 'balneario rincao',
 'balneário arroio do silva',
 'balneário barra do sul',
 'balneário camboriú',
 'balneário gaivota',
 'balneário pinhal',
 'balneário piçarras',
 'balneário rincão',
 'balsa nova',
 'balsamo',
 'balsas',
 'bambui',
 'bambuí',
 'banabuiu',
 'banabuiú',
 'bananal',
 'bananeiras',
 'bandeira',
 'bandeira do sul',
 'bandeirante',
 'bandeirantes',
 "bandeirantes d'oeste",
 'bandeirantes do tocantins',
 'bannach',
 'banquete',
 'banzae',
 'banzaê',
 'barao',
 'barao ataliba nogueira',
 'barao de antonina',
 'barao de cocais',
 'barao de cotegipe',
 'barao de grajau',
 'barao de juparana',
 'barao de melgaco',
 'barao de monte alto',
 'barao do triunfo',
 'barauna',
 'baraúna',
 'barbacena',
 'barbalha',
 'barbosa',
 'barbosa ferraz',
 'barcarena',
 'barcelona',
 'barcelos',
 'bariri',
 'barra',
 'barra bonita',
 "barra d'alcantara",
 "barra d'alcântara",
 'barra da estiva',
 'barra de  santo antônio',
 'barra de guabiraba',
 'barra de santa rosa',
 'barra de santana',
 'barra de santo antonio',
 'barra de santo antônio',
 'barra de sao francisco',
 'barra de sao joao',
 'barra de sao miguel',
 'barra de são francisco',
 'barra de são joão',
 'barra de são miguel',
 'barra do ariranha',
 'barra do bugres',
 'barra do chapeu',
 'barra do chapéu',
 'barra do choca',
 'barra do choça',
 'barra do corda',
 'barra do cuiete',
 'barra do garcas',
 'barra do garças',
 'barra do guarita',
 'barra do jacare',
 'barra do jacaré',
 'barra do jacuipe',
 'barra do mendes',
 'barra do pirai',
 'barra do piraí',
 'barra do quarai',
 'barra do quaraí',
 'barra do ribeiro',
 'barra do rio azul',
 'barra do rocha',
 'barra do tarrachil',
 'barra do turvo',
 'barra dos coqueiros',
 'barra feliz',
 'barra funda',
 'barra longa',
 'barra mansa',
 'barra velha',
 'barracao',
 'barracão',
 'barrado quarai',
 'barras',
 'barreira',
 'barreiras',
 'barreiras do piaui',
 'barreiras do piauí',
 'barreirinhas',
 'barreiro branco',
 'barreiros',
 'barretos',
 'barrinha',
 'barro',
 'barro alto',
 'barro duro',
 'barro preto',
 'barrocas',
 'barrolandia',
 'barrolândia',
 'barroquinha',
 'barros cassal',
 'barroso',
 'barueri',
 'barão',
 'barão ataliba nogueira',
 'barão de antonina',
 'barão de cocais',
 'barão de cotegipe',
 'barão de grajaú',
 'barão de juparana',
 'barão de monte alto',
 'barão do triunfo',
 'bastos',
 'bataguassu',
 'bataipora',
 'batalha',
 'batatais',
 'batateira',
 'bataypora',
 'batayporã',
 'batinga',
 'baturite',
 'baturité',
 'bauru',
 'bayeux',
 'baía formosa',
 'bebedouro',
 'beberibe',
 'bela cruz',
 'bela vista',
 'bela vista da caroba',
 'bela vista de goias',
 'bela vista de goiás',
 'bela vista de minas',
 'bela vista do maranhao',
 'bela vista do paraiso',
 'bela vista do paraíso',
 'bela vista do piaui',
 'bela vista do piauí',
 'bela vista do toldo',
 'belagua',
 'belem',
 'belem de maria',
 'belem de sao francisco',
 'belem do brejo do cruz',
 'belem do piaui',
 'belem do sao francisco',
 'belford roxo',
 'belmiro braga',
 'belmonte',
 'belo campo',
 'belo horizonta',
 'belo horizonte',
 'belo jardim',
 'belo oriente',
 'belo vale',
 'belterra',
 'belágua',
 'belém',
 'belém do são francisco',
 'beneditinos',
 'benedito leite',
 'benedito novo',
 'benevides',
 'benfica',
 'benjamin constant',
 'benjamin constant do sul',
 'bento de abreu',
 'bento fernandes',
 'bento goncalves',
 'bento gonçalves',
 'bentopolis',
 'bentópolis de minas',
 'bequimao',
 'bequimão',
 'berilo',
 'berizal',
 'bernardino batista',
 'bernardino de campos',
 'bernardo do mearim',
 'bernardo sayao',
 'bernardo sayão',
 'bertioga',
 'bertolinia',
 'bertolínia',
 'bertopolis',
 'bertópolis',
 'betania',
 'betania do piaui',
 'betim',
 'betânia',
 'betânia do piauí',
 'bezerros',
 'bh',
 'bias fortes',
 'bicas',
 'bicuiba',
 'biguacu',
 'biguaçu',
 'bilac',
 'biquinhas',
 'birigui',
 'birigüi',
 'biritiba mirim',
 'biritiba-mirim',
 'biritinga',
 'bitupita',
 'bituruna',
 'bizarra',
 'blumenau',
 'boa esperanca',
 'boa esperanca do iguacu',
 'boa esperanca do sul',
 'boa esperança',
 'boa esperança do iguaçu',
 'boa esperança do sul',
 'boa hora',
 'boa nova',
 'boa saude',
 'boa sorte',
 'boa uniao',
 'boa uniao de itabirinha',
 'boa união de itabirinha',
 'boa ventura',
 'boa ventura de sao roque',
 'boa ventura de são roque',
 'boa viagem',
 'boa vista',
 'boa vista da aparecida',
 'boa vista das missoes',
 'boa vista das missões',
 'boa vista de minas',
 'boa vista do burica',
 'boa vista do buricá',
 'boa vista do cadeado',
 'boa vista do gurupi',
 'boa vista do incra',
 'boa vista do ramos',
 'boa vista do sul',
 'boa vista do tupim',
 'boa vista dos andradas',
 'boca da mata',
 'boca do acre',
 'bocaina',
 'bocaina de minas',
 'bocaina do sul',
 'bocaiuva',
 'bocaiuva do sul',
 'bocaiúva',
 'bocaiúva do sul',
 'bocaína do sul',
 'bodo',
 'bodoco',
 'bodocó',
 'bodoquena',
 'bofete',
 'boituva',
 'bom conselho',
 'bom despacho',
 'bom fim do bom jesus',
 'bom jardim',
 'bom jardim da serra',
 'bom jardim de goias',
 'bom jardim de goiás',
 'bom jardim de minas',
 'bom jardim do sul',
 'bom jesus',
 'bom jesus da lapa',
 'bom jesus da penha',
 'bom jesus da serra',
 'bom jesus das selvas',
 'bom jesus de goias',
 'bom jesus do amparo',
 'bom jesus do araguaia',
 'bom jesus do galho',
 'bom jesus do itabapoana',
 'bom jesus do norte',
 'bom jesus do sul',
 'bom jesus do tocantins',
 'bom jesus dos perdoes',
 'bom jesus dos perdões',
 'bom lugar',
 'bom principio',
 'bom principio do piaui',
 'bom princípio',
 'bom progresso',
 'bom repouso',
 'bom retiro',
 'bom retiro da esperanca',
 'bom retiro do sul',
 'bom sucesso',
 'bom sucesso de itarare',
 'bom sucesso de itararé',
 'bom sucesso do sul',
 'bombinhas',
 'bonfim',
 'bonfim paulista',
 'bonfinopolis',
 'bonfinopolis de minas',
 'bonfinópolis',
 'bonfinópolis de minas',
 'boninal',
 'bonito',
 'bonito de minas',
 'bonito de santa fe',
 'bonopolis',
 'bonópolis',
 'boqueirao',
 'boqueirao do leao',
 'boqueirao do piaui',
 'boqueirão do leão',
 'boqueirão do piauí',
 'boquim',
 'boquira',
 'boraceia',
 'boracéia',
 'borba',
 ...]

In [18]:
donnees.city = donnees.city.apply(nettoyer)

In [19]:
list(donnees.city.sort_values().unique())

['4o centenario',
 'abadia de goias',
 'abadia dos dourados',
 'abadiania',
 'abaete',
 'abaetetuba',
 'abaiara',
 'abaira',
 'abare',
 'abatia',
 'abdon batista',
 'abel figueiredo',
 'abelardo luz',
 'abrantes',
 'abre campo',
 'abreu e lima',
 'abreulandia',
 'abreus',
 'acaiaca',
 'acailandia',
 'acajutiba',
 'acara',
 'acarape',
 'acarau',
 'acari',
 'acaua',
 'acegua',
 'acioli',
 'acopiara',
 'acorizal',
 'acrelandia',
 'acreuna',
 'acu',
 'acu da torre',
 'acucena',
 'acupe',
 'adamantina',
 'adao colares',
 'adelandia',
 'adhemar de barros',
 'adolfo',
 'adrianopolis',
 'adustina',
 'afogados da ingazeira',
 'afonso arinos',
 'afonso bezerra',
 'afonso claudio',
 'afonso cunha',
 'afranio',
 'afua',
 'agisse',
 'agrestina',
 'agricolandia',
 'agrolandia',
 'agronomica',
 'agua azul do norte',
 'agua boa',
 'agua branca',
 'agua branca de minas',
 'agua clara',
 'agua comprida',
 'agua doce',
 'agua doce do maranhao',
 'agua doce do norte',
 'agua fria',
 'agua fria de goias',
 'agua limpa',
 'agua nova',
 'agua preta',
 'agua santa',
 'agua vermelha',
 'aguai',
 'aguanil',
 'aguas belas',
 'aguas claras',
 'aguas da prata',
 'aguas de chapeco',
 'aguas de lindoia',
 'aguas de santa barbara',
 'aguas de sao pedro',
 'aguas ferreas',
 'aguas formosas',
 'aguas frias',
 'aguas lindas de goias',
 'aguas mornas',
 'aguas vermelhas',
 'agudo',
 'agudos',
 'agudos do sul',
 'aguia branca',
 'aguiar',
 'aguiarnopolis',
 'agulha',
 'aimores',
 'aiquara',
 'aiuaba',
 'aiuruoca',
 'ajuricaba',
 'alagoa',
 'alagoa grande',
 'alagoa nova',
 'alagoinha',
 'alagoinha do piaui',
 'alagoinhas',
 'alambari',
 'albertina',
 'alberto isaacson',
 'alcantara',
 'alcantaras',
 'alcantil',
 'alcinopolis',
 'alcobaca',
 'aldeia',
 'aldeias altas',
 'alecrim',
 'alegre',
 'alegrete',
 'alegrete do piaui',
 'alegria',
 'alem paraiba',
 'alenquer',
 'alexandra',
 'alexandria',
 'alexandrita',
 'alexania',
 'alfenas',
 'alfredo chaves',
 'alfredo guedes',
 'alfredo marcondes',
 'alfredo vasconcelos',
 'alfredo wagner',
 'algodao de jandaira',
 'algodoes',
 'alhandra',
 'alianca',
 'alianca do tocantins',
 'almadina',
 'almas',
 'almeirim',
 'almenara',
 'almino afonso',
 'almirante tamandare',
 'almirante tamandare do sul',
 'aloandia',
 'alpercata',
 'alpestre',
 'alpinopolis',
 'alta alegre dos parecis',
 'alta floresta',
 'alta floresta do oeste',
 'alta floresta doeste',
 'altair',
 'altamira',
 'altamira do maranhao',
 'altamira do parana',
 'altaneira',
 'alterosa',
 'altinho',
 'altinopolis',
 'alto alegre',
 'alto alegre do iguacu',
 'alto alegre do maranhao',
 'alto alegre do pindare',
 'alto alegre dos parecis',
 'alto araguaia',
 'alto bela vista',
 'alto boa vista',
 'alto calcado',
 'alto caparao',
 'alto do rodrigues',
 'alto feliz',
 'alto garcas',
 'alto horizonte',
 'alto jequitiba',
 'alto longa',
 'alto maranhao',
 'alto mutum preto',
 'alto paraguai',
 'alto paraiso',
 'alto paraiso de goias',
 'alto parana',
 'alto parnaiba',
 'alto piquiri',
 'alto rio doce',
 'alto rio novo',
 'alto santo',
 'alto taquari',
 'altonia',
 'altos',
 'aluminio',
 'alvacao',
 'alvaraes',
 'alvarenga',
 'alvares florence',
 'alvares machado',
 'alvaro de carvalho',
 'alvinlandia',
 'alvinopolis',
 'alvorada',
 'alvorada de minas',
 'alvorada do gurgueia',
 'alvorada do norte',
 'alvorada do oeste',
 'alvorada do sul',
 'alvorada doeste',
 'amambai',
 'amanari',
 'amandina',
 'amanhece',
 'amapa',
 'amapa do maranhao',
 'amapari',
 'amapora',
 'amaraji',
 'amaral ferrador',
 'amaralina',
 'amarante',
 'amarante do maranhao',
 'amarantina',
 'amargosa',
 'amatura',
 'amelia rodrigues',
 'america dourada',
 'americana',
 'americano',
 'americano do brasil',
 'americo brasiliense',
 'americo de campos',
 'ametista do sul',
 'amontada',
 'amorinopolis',
 'amparo',
 'amparo da serra',
 'amparo de sao francisco',
 'ampere',
 'ana dias',
 'anadia',
 'anage',
 'anahy',
 'anajas',
 'anajatuba',
 'analandia',
 'anama',
 'ananas',
 'ananindeua',
 'anapolis',
 'anapu',
 'anapurus',
 'anastacio',
 'anaurilandia',
 'anchieta',
 'andarai',
 'andira',
 'andorinha',
 'andradas',
 'andrade pinto',
 'andradina',
 'andre da rocha',
 'andrelandia',
 'andrequice',
 'angatuba',
 'angelandia',
 'angelica',
 'angelim',
 'angelina',
 'angical',
 'angical do piaui',
 'angico',
 'angicos',
 'angra dos reis',
 'anguera',
 'anguereta',
 'angulo',
 'angustura',
 'anhandui',
 'anhanguera',
 'anhembi',
 'anhumas',
 'anicuns',
 'anisio de abreu',
 'anita garibaldi',
 'anitapolis',
 'anori',
 'anta',
 'anta gorda',
 'antas',
 'antonina',
 'antonina do norte',
 'antonio almeida',
 'antonio cardoso',
 'antonio carlos',
 'antonio dias',
 'antonio goncalves',
 'antonio joao',
 'antonio martins',
 'antonio olinto',
 'antonio pereira',
 'antonio prado',
 'antonio prado de minas',
 'antunes',
 'antunes igaratinga',
 'aparecida',
 'aparecida d oeste',
 'aparecida de goiania',
 'aparecida de minas',
 'aparecida de monte alto',
 'aparecida de sao manuel',
 'aparecida do rio doce',
 'aparecida do rio negro',
 'aparecida do taboado',
 'aparecida doeste',
 'aperibe',
 'apeu',
 'apiaca',
 'apiacas',
 'apiai',
 'apicumacu',
 'apiuna',
 'apodi',
 'apora',
 'apore',
 'apuarema',
 'apucarana',
 'apui',
 'apuiares',
 'aquidaba',
 'aquidaban',
 'aquidauana',
 'aquiraz',
 'arabuta',
 'aracagi',
 'aracai',
 'aracaju',
 'aracariguama',
 'aracas',
 'aracati',
 'aracatu',
 'aracatuba',
 'arace',
 'araci',
 'aracitaba',
 'aracoiaba',
 'aracoiaba da serra',
 'aracruz',
 'aracu',
 'aracuai',
 'aragarcas',
 'aragoiania',
 'aragominas',
 'araguacema',
 'araguacu',
 'araguaia',
 'araguaiana',
 'araguaina',
 'araguainha',
 'araguana',
 'araguapaz',
 'araguari',
 'araguatins',
 'araioses',
 'aral moreira',
 'aramari',
 'arambare',
 'arame',
 'aramina',
 'arandu',
 'arantina',
 'arapei',
 'arapiraca',
 'arapoema',
 'araponga',
 'arapongas',
 'arapora',
 'arapoti',
 'arapua',
 'araputanga',
 'araquari',
 'arara',
 'ararangua',
 'araraquara',
 'araras',
 'ararenda',
 'arari',
 'ararica',
 'araripe',
 'araripina',
 'araruama',
 'araruna',
 'arataca',
 'aratiba',
 'aratuba',
 'aratuipe',
 'araua',
 'araucaria',
 'araujos',
 'araxa',
 'arceburgo',
 'arco verde',
 'arcoiris',
 'arcos',
 'arcoverde',
 'areado',
 'areal',
 'arealva',
 'areia',
 'areia branca',
 'areia branca dos assis',
 'areia de baraunas',
 'areial',
 'areias',
 'areiopolis',
 'arembepe',
 'arenapolis',
 'arenopolis',
 'arez',
 'argirita',
 'aricanduva',
 'arinos',
 'aripuana',
 'ariquemes',
 'ariranha',
 'ariranha do ivai',
 'armacao de buzios',
 'armacao dos buzios',
 'armazem',
 'arneiroz',
 'aroazes',
 'aroeiras',
 'arraial',
 'arraial d ajuda',
 'arraial dajuda',
 'arraial do cabo',
 'arraias',
 'arroio do meio',
 'arroio do padre',
 'arroio do sal',
 'arroio do tigre',
 'arroio dos ratos',
 'arroio grande',
 'arroio trinta',
 'arrozal',
 'artur nogueira',
 'aruana',
 'aruja',
 'arvoredo',
 'arvorezinha',
 'ascurra',
 'aspasia',
 'assai',
 'assare',
 'assis',
 'assis brasil',
 'assis chateaubriand',
 'assuncao',
 'assuncao do piaui',
 'astolfo dutra',
 'astorga',
 'atalaia',
 'atalaia do norte',
 'atalanta',
 'ataleia',
 'atibaia',
 'atilio vivacqua',
 'augustinopolis',
 'augusto correa',
 'augusto de lima',
 'augusto pestana',
 'aurea',
 'aurelino leal',
 'auriflama',
 'aurilandia',
 'aurora',
 'aurora do iguacu',
 'aurora do para',
 'aurora do tocantins',
 'autazes',
 'avai',
 'avai do jacinto',
 'avanhandava',
 'avare',
 'avelar',
 'avelino lopes',
 'avelinopolis',
 'axixa',
 'axixa do tocantins',
 'azambuja',
 'azurita',
 'babaculandia',
 'bacabal',
 'bacabeira',
 'bacaxa',
 'bacaxa saquarema distrito',
 'bacuri',
 'bacurituba',
 'bady bassitt',
 'baependi',
 'bage',
 'bagre',
 'baguacu',
 'baguari',
 'baia formosa',
 'baianopolis',
 'baiao',
 'baixa grande',
 'baixa grande do ribeiro',
 'baixio',
 'baixo guandu',
 'balbinos',
 'baldim',
 'baliza',
 'balneario arroio do silva',
 'balneario barra do sul',
 'balneario camboriu',
 'balneario de picarras',
 'balneario gaivota',
 'balneario picarras',
 'balneario pinhal',
 'balneario rincao',
 'balsa nova',
 'balsamo',
 'balsas',
 'bambui',
 'banabuiu',
 'bananal',
 'bananeiras',
 'bandeira',
 'bandeira do sul',
 'bandeirante',
 'bandeirantes',
 'bandeirantes do tocantins',
 'bandeirantes doeste',
 'bannach',
 'banquete',
 'banzae',
 'barao',
 'barao ataliba nogueira',
 'barao de antonina',
 'barao de cocais',
 'barao de cotegipe',
 'barao de grajau',
 'barao de juparana',
 'barao de melgaco',
 'barao de monte alto',
 'barao do triunfo',
 'barauna',
 'barbacena',
 'barbalha',
 'barbosa',
 'barbosa ferraz',
 'barcarena',
 'barcelona',
 'barcelos',
 'bariri',
 'barra',
 'barra bonita',
 'barra da estiva',
 'barra dalcantara',
 'barra de guabiraba',
 'barra de santa rosa',
 'barra de santana',
 'barra de santo antonio',
 'barra de sao francisco',
 'barra de sao joao',
 'barra de sao miguel',
 'barra do ariranha',
 'barra do bugres',
 'barra do chapeu',
 'barra do choca',
 'barra do corda',
 'barra do cuiete',
 'barra do garcas',
 'barra do guarita',
 'barra do jacare',
 'barra do jacuipe',
 'barra do mendes',
 'barra do pirai',
 'barra do quarai',
 'barra do ribeiro',
 'barra do rio azul',
 'barra do rocha',
 'barra do tarrachil',
 'barra do turvo',
 'barra dos coqueiros',
 'barra feliz',
 'barra funda',
 'barra longa',
 'barra mansa',
 'barra velha',
 'barracao',
 'barrado quarai',
 'barras',
 'barreira',
 'barreiras',
 'barreiras do piaui',
 'barreirinhas',
 'barreiro branco',
 'barreiros',
 'barretos',
 'barrinha',
 'barro',
 'barro alto',
 'barro duro',
 'barro preto',
 'barrocas',
 'barrolandia',
 'barroquinha',
 'barros cassal',
 'barroso',
 'barueri',
 'bastos',
 'bataguassu',
 'bataipora',
 'batalha',
 'batatais',
 'batateira',
 'bataypora',
 'batinga',
 'baturite',
 'bauru',
 'bayeux',
 'bebedouro',
 'beberibe',
 'bela cruz',
 'bela vista',
 'bela vista da caroba',
 'bela vista de goias',
 'bela vista de minas',
 'bela vista do maranhao',
 'bela vista do paraiso',
 'bela vista do piaui',
 'bela vista do toldo',
 'belagua',
 'belem',
 'belem de maria',
 'belem de sao francisco',
 'belem do brejo do cruz',
 'belem do piaui',
 'belem do sao francisco',
 'belford roxo',
 'belmiro braga',
 'belmonte',
 'belo campo',
 'belo horizonta',
 'belo horizonte',
 'belo jardim',
 'belo oriente',
 'belo vale',
 'belterra',
 'beneditinos',
 'benedito leite',
 'benedito novo',
 'benevides',
 'benfica',
 'benjamin constant',
 'benjamin constant do sul',
 'bento de abreu',
 'bento fernandes',
 'bento goncalves',
 'bentopolis',
 'bentopolis de minas',
 'bequimao',
 'berilo',
 'berizal',
 'bernardino batista',
 'bernardino de campos',
 'bernardo do mearim',
 'bernardo sayao',
 'bertioga',
 'bertolinia',
 'bertopolis',
 'betania',
 'betania do piaui',
 'betim',
 'bezerros',
 'bh',
 'bias fortes',
 'bicas',
 'bicuiba',
 'biguacu',
 'bilac',
 'biquinhas',
 'birigui',
 'biritiba mirim',
 'biritibamirim',
 'biritinga',
 'bitupita',
 'bituruna',
 'bizarra',
 'blumenau',
 'boa esperanca',
 'boa esperanca do iguacu',
 'boa esperanca do sul',
 'boa hora',
 'boa nova',
 'boa saude',
 'boa sorte',
 'boa uniao',
 'boa uniao de itabirinha',
 'boa ventura',
 'boa ventura de sao roque',
 'boa viagem',
 'boa vista',
 'boa vista da aparecida',
 'boa vista das missoes',
 'boa vista de minas',
 'boa vista do burica',
 'boa vista do cadeado',
 'boa vista do gurupi',
 'boa vista do incra',
 'boa vista do ramos',
 'boa vista do sul',
 'boa vista do tupim',
 'boa vista dos andradas',
 'boca da mata',
 'boca do acre',
 'bocaina',
 'bocaina de minas',
 'bocaina do sul',
 'bocaiuva',
 'bocaiuva do sul',
 'bodo',
 'bodoco',
 'bodoquena',
 'bofete',
 'boituva',
 'bom conselho',
 'bom despacho',
 'bom fim do bom jesus',
 'bom jardim',
 'bom jardim da serra',
 'bom jardim de goias',
 'bom jardim de minas',
 'bom jardim do sul',
 'bom jesus',
 'bom jesus da lapa',
 'bom jesus da penha',
 'bom jesus da serra',
 'bom jesus das selvas',
 'bom jesus de goias',
 'bom jesus do amparo',
 'bom jesus do araguaia',
 'bom jesus do galho',
 'bom jesus do itabapoana',
 'bom jesus do norte',
 'bom jesus do sul',
 'bom jesus do tocantins',
 'bom jesus dos perdoes',
 'bom lugar',
 'bom principio',
 'bom principio do piaui',
 'bom progresso',
 'bom repouso',
 'bom retiro',
 'bom retiro da esperanca',
 'bom retiro do sul',
 'bom sucesso',
 'bom sucesso de itarare',
 'bom sucesso do sul',
 'bombinhas',
 'bonfim',
 'bonfim paulista',
 'bonfinopolis',
 'bonfinopolis de minas',
 'boninal',
 'bonito',
 'bonito de minas',
 'bonito de santa fe',
 'bonopolis',
 'boqueirao',
 'boqueirao do leao',
 'boqueirao do piaui',
 'boquim',
 'boquira',
 'boraceia',
 'borba',
 'borborema',
 'borda da mata',
 'borda do campo',
 'borebi',
 'borrazopolis',
 'bossoroca',
 'botelho',
 'botelhos',
 'botucatu',
 'botumirim',
 'botupora',
 'botuvera',
 'bozano',
 'braco do norte',
 'braco do rio',
 'braco do trombudo',
 'braga',
 'braganca',
 'braganca paulista',
 'braganey',
 'bragantina',
 'branquinha',
 'bras pires',
 'brasil novo',
 'brasilandia',
 'brasilandia de minas',
 'brasilandia do sul',
 'brasilandia do tocantins',
 'brasileia',
 'brasileira',
 'brasilia',
 'brasilia de minas',
 'brasitania',
 'brasnorte',
 'brasopolis',
 'brauna',
 'braunas',
 'brazabrantes',
 'brazlandia',
 'brazopolis',
 'brejao',
 'brejetuba',
 'brejinho',
 'brejinho de nazare',
 'brejo',
 'brejo alegre',
 'brejo bonito',
 'brejo da madre de deus',
 'brejo de areia',
 'brejo do cruz',
 'brejo do piaui',
 'brejo dos santos',
 'brejo grande',
 'brejo grande do araguaia',
 'brejo santo',
 'brejoes',
 'brejolandia',
 'breu branco',
 'breves',
 'britania',
 'brochier',
 'brodowski',
 'brotas',
 'brotas de macaubas',
 'brumadinho',
 'brumado',
 'brunopolis',
 'brusque',
 'bueno brandao',
 'buenopolis',
 'buenos aires',
 'buerarema',
 'bugre',
 'buique',
 'bujari',
 'bujaru',
 'burarama',
 'buri',
 'buritama',
 'buriti',
 'buriti alegre',
 'buriti bravo',
 'buriti de goias',
 'buriti do tocantins',
 'buriti dos lopes',
 'buriti dos montes',
 'buriticupu',
 'buritinopolis',
 'buritirama',
 'buritirana',
 'buritis',
 'buritizal',
 'buritizeiro',
 'butia',
 'buzios',
 'caapiranga',
 'caapora',
 'caarapo',
 'caatiba',
 'cabaceiras',
 'cabaceiras do paraguacu',
 'cabeceira grande',
 'cabeceiras',
 'cabeceiras do piaui',
 'cabedelo',
 'cabixi',
 'cabo de santo agostinho',
 'cabo frio',
 'cabo verde',
 'cabralia paulista',
 'cabreuva',
 'cabrobo',
 'cacador',
 'cacapava',
 'cacapava do sul',
 'cacaratiba',
 'cacarema',
 'cacaulandia',
 'cacequi',
 'caceres',
 'cachoeira',
 'cachoeira alegre',
 'cachoeira alta',
 'cachoeira da prata',
 'cachoeira de goias',
 'cachoeira de minas',
 'cachoeira de pajeu',
 'cachoeira de piria',
 'cachoeira de santa cruz',
 'cachoeira do arari',
 'cachoeira do brumado',
 'cachoeira do campo',
 'cachoeira do piria',
 'cachoeira do sul',
 'cachoeira dos indios',
 'cachoeira dourada',
 'cachoeira paulista',
 'cachoeiras de macacu',
 'cachoeirinha',
 'cachoeiro de itapemirim',
 'cacimba de dentro',
 'cacimbas',
 'cacimbinhas',
 'cacique doble',
 'cacoal',
 'caconde',
 'cacu',
 'cacule',
 'caem',
 'caetano mendes',
 'caetanopolis',
 'caetanos',
 'caete',
 'caetes',
 'caetite',
 'cafarnaum',
 'cafe',
 'cafeara',
 'cafelandia',
 'cafezal do sul',
 'caiabu',
 'caiana',
 'caiaponia',
 'caibate',
 'caibi',
 'caicara',
 'caicara do norte',
 'caicara do rio do vento',
 'caico',
 'caieiras',
 'cairu',
 'caiua',
 'cajamar',
 'cajapio',
 'cajari',
 'cajati',
 'cajazeiras',
 'cajazeiras do piaui',
 'cajobi',
 'cajueiro',
 'cajueiro da praia',
 'cajuri',
 'cajuru',
 'calcado',
 'calcoene',
 'caldas',
 'caldas brandao',
 'caldas novas',
 'caldazinha',
 'caldeirao grande',
 'caldeirao grande do piaui',
 'calheiros',
 'california',
 'california da barra',
 'california da barra barra do pirai',
 'calixto',
 'calmon',
 'calumbi',
 'camacan',
 'camacari',
 'camacho',
 'camalau',
 'camamu',
 'camanducaia',
 'camapua',
 'camaqua',
 'camaragibe',
 'camargo',
 'cambara',
 'cambara do sul',
 'cambe',
 'cambiasca',
 'cambira',
 'camboriu',
 'cambuci',
 'cambui',
 'cambuquira',
 'camela',
 'cameta',
 'camocim',
 'camocim de sao felix',
 'campanario',
 'campanha',
 'campestre',
 'campestre da serra',
 ...]

In [20]:
donnees[['zip_code','city','state']].drop_duplicates().shape

(19581, 3)

In [21]:
donnees.zip_code.nunique()

19015

In [22]:
donnees[['zip_code','city','state']].drop_duplicates().shape

(19581, 3)

In [23]:
geographie = donnees.groupby('zip_code').agg({
    'lat': ['min', 'median', 'max'],
    'lng': ['min', 'median', 'max'],
    'city': 'first',
    'state': 'first'
}).reset_index()
geographie.columns = [geographie.columns[0][0]]+[ col[0]+'_'+col[1] for col in geographie.columns[1:] ]
geographie.columns = [col.replace('_first','').replace('_median','') for col in geographie.columns]
geographie = geographie[['zip_code','city','state','lat','lng','lat_min','lat_max','lng_min','lng_max']]
geographie.head()

,zip_code,city,state,lat,lng,lat_min,lat_max,lng_min,lng_max
0,1001,sao paulo,São Paulo,-23.550381,-46.634027,-23.551427,-23.549292,-46.634410,-46.633559
1,1002,sao paulo,São Paulo,-23.548551,-46.635072,-23.548878,-23.544641,-46.636361,-46.633180
2,1003,sao paulo,São Paulo,-23.548977,-46.635313,-23.549083,-23.548901,-46.637157,-46.634862
3,1004,sao paulo,São Paulo,-23.549535,-46.634771,-23.550765,-23.549181,-46.635371,-46.634057
4,1005,sao paulo,São Paulo,-23.549612,-46.636532,-23.549980,-23.548758,-46.638411,-46.634768

In [24]:
geographie.zip_code.nunique()

19015

In [25]:
donnees = geographie

## Sauvegarde en parquet

In [26]:
donnees.to_parquet('./ecommerce/geolocation.parquet',compression='gzip', engine='pyarrow')

In [27]:
pd.read_parquet('./ecommerce/geolocation.parquet').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19015 entries, 0 to 19014
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   zip_code  19015 non-null  int32
 1   city      19015 non-null  object
 2   state     19015 non-null  object
 3   lat       19015 non-null  float64
 4   lng       19015 non-null  float64
 5   lat_min   19015 non-null  float64
 6   lat_max   19015 non-null  float64
 7   lng_min   19015 non-null  float64
 8   lng_max   19015 non-null  float64
dtypes: float64(6), int32(1), object(2)
memory usage: 1.2+ MB

In [28]:
!dir ecommerce

 Le volume dans le lecteur C s'appelle Windows
 Le num‚ro de s‚rie du volume est 7E56-F105

 R‚pertoire de C:\dev\PythonFormation\donnees\ecommerce

23/09/2026  15:33    <DIR>          .
04/06/2026  10:58    <DIR>          ..
23/09/2026  15:55         4ÿ513ÿ352 customers.parquet
09/10/2025  10:23        14ÿ319ÿ809 etoile01.parquet
09/10/2025  15:54        17ÿ371ÿ074 etoile02.parquet
09/10/2025  10:32        18ÿ160ÿ225 etoile03.parquet
23/09/2026  16:21         1ÿ118ÿ998 geolocation.parquet
23/09/2026  15:25         4ÿ803ÿ098 items.parquet
23/09/2026  15:09         9ÿ538ÿ920 orders.parquet
23/09/2026  15:29         9ÿ991ÿ736 orders_payments.parquet
23/09/2026  15:29        13ÿ250ÿ586 orders_payments_items.parquet
23/09/2026  15:27         2ÿ648ÿ862 payments.parquet
23/09/2026  15:27         2ÿ464ÿ323 paymentsI.parquet
23/09/2026  15:51           959ÿ732 products.parquet
23/09/2026  15:47         7ÿ520ÿ329 reviews.parquet
23/09/2026  15:47         2ÿ829ÿ017 reviews_p.parquet
23/09/2026  15:59            91ÿ207 sellers.parquet
07/10/2025  17:33        13ÿ726ÿ242 tp08.agregat.parquet
07/10/2025  17:33        18ÿ160ÿ225 tp08.complet.parquet
09/10/2025  12:13           377ÿ286 Ventes.Regions.html
              18 fichier(s)      141ÿ845ÿ021 octets
               2 R‚p(s)  155ÿ008ÿ778ÿ240 octets libres

## Sauvegarde dans la base de données

In [29]:
donnees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19015 entries, 0 to 19014
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   zip_code  19015 non-null  int32
 1   city      19015 non-null  object
 2   state     19015 non-null  object
 3   lat       19015 non-null  float64
 4   lng       19015 non-null  float64
 5   lat_min   19015 non-null  float64
 6   lat_max   19015 non-null  float64
 7   lng_min   19015 non-null  float64
 8   lng_max   19015 non-null  float64
dtypes: float64(6), int32(1), object(2)
memory usage: 1.2+ MB

In [37]:
donnees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19015 entries, 0 to 19014
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   zip_code  19015 non-null  int32
 1   city      19015 non-null  object
 2   state     19015 non-null  object
 3   lat_min   19015 non-null  float64
 4   lat_max   19015 non-null  float64
 5   lat       19015 non-null  float64
 6   lng_min   19015 non-null  float64
 7   lng_max   19015 non-null  float64
 8   lng       19015 non-null  float64
dtypes: float64(6), int32(1), object(2)
memory usage: 1.2+ MB

In [30]:
donnees.to_sql('geolocation',
               # schema='ebrasil',
               con=connection,
               if_exists='replace',
               index=False,
               dtype={ 
                        "zip_code" :sqlalchemy.types.Integer(),  
                        "city"     :sqlalchemy.types.String(80),
                        "state"    :sqlalchemy.types.String(80), 
                        "lat"      :sqlalchemy.types.Float(),
                        "lng"      :sqlalchemy.types.Float(),
                        "lat_min"  :sqlalchemy.types.Float(),
                        "lat_max"  :sqlalchemy.types.Float(),
                        "lng_min"  :sqlalchemy.types.Float(),
                        "lng_max"  :sqlalchemy.types.Float()
               })

15

In [31]:
requete  = "select count(*) from geolocation"
pd.read_sql_query(requete, connection)

   count
0  19015